def get_instruction(task_type, task_name):
    if task_type == "STS":
        return "Retrieve semantically similar text."

    if task_type == "BitextMining":
        return "Retrieve parallel sentences."

    if task_type == "PairClassification":
        return "Retrieve semantically similar text."

    if task_type == "MultiLabelTextClassification":
        instruction_dict = {
            "Prachathai67kMultiLabelTextClassification": "Classify the given news articles into its appropriate topics",
            "TrueVoiceIntentMultiLabelTextClassification": "Given a call center query, find the corresponding intents",
            "IndoCASAMultiLabelTextClassification": "Classify the sentiment expressed in the given car reviews text from the online automobile platform",
            "IndoHoASAMultiLabelTextClassification": "Classify the sentiment expressed in the given hotel reviews text from the hotel aggregator platform",
            "VLSP2018SAHotelMultiLabelTextClassification": "Classify the sentiment expressed in the given hotel reviews text",
            "VLSP2018SARestaurantMultiLabelTextClassification": "Classify the sentiment expressed in the given restaurant reviews text",
            "DengueMultiLabelTextClassification": "Classify the given tweets into its appropriate classes",
            "IndoHateSpeechMultiLabelClassification": "Classify the given tweets into its appropriate classes",
            "IndoNetifierMultiLabelClassification": "Classify the given social media text toxicity into its appropriate classes",
            "GKLMIPNewsMultiLabelClassification": "Classify the given news into its appropriate classes",
        }

        return instruction_dict.get(task_name)

    if task_type == "QARetrieval":
        instruction_dict = {
            "ThaiTyDiQAQARetrieval": "Given a passage that is guaranteed to contain the answer, retrieve relevant passages that answer the query.",
            "IndoTyDiQAQARetrieval": "Given a passage that is guaranteed to contain the answer, retrieve relevant passages that answer the query.",
            "ThaiMIRACLQARetrieval": "Given a query and a set of documents, retrieve the documents most relevant to answering the query.",
            "IndoMIRACLQARetrieval": "Given a query and a set of documents, retrieve the documents most relevant to answering the query.",
            "ThaiXQuADQARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "VietnameseXQuADQARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "ViQuAD2_0QARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "VietnameseMLQAQARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "ThaiMLDRQARetrieval": "Given a query and a long documents, retrieve the documents most relevant to answering the query.",
            "TamilIndicQAQARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "IAppWikiQARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "BurmeseMicrobiology1KQARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "MyanmarAgricutlure1KQARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "BurmeseAskCovidDrBotQARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "IndoACIQuADQARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "IndoQASiNaQARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "IndoIDKMRCQARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "IndoQAQARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "WangchanXLegalThaiCCLRAGQARetrieval": "Given a question and a passage, retrieve the most relevant passage that answer the question.",
            "WangchanXSyntheticInstructThai120kQARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "ThaiWikiQAQARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "MalayChatGPTOpenQAQARetrieval": "Given a question and a paragraph, retrieve the most relevant paragraph that answer the question.",
        }

        return instruction_dict.get(task_name)

    if task_type == "TextClassification":
        instruction_dict = {
            "ThaiIntentTextClassification": "Given a user utterance as query, find the user intents",
            "IndoIntentTextClassification": "Given a user utterance as query, find the user intents",
            "VietnameseIntentTextClassification": "Given a user utterance as query, find the user intents",
            "TagalogIntentTextClassification": "Given a user utterance as query, find the user intents",
            "MalayIntentTextClassification": "Given a user utterance as query, find the user intents",
            "KhmerIntentTextClassification": "Given a user utterance as query, find the user intents",
            "TamilIntentTextClassification": "Given a user utterance as query, find the user intents",
            "ThaiScenarioTextClassification": "Given a user utterance as query, find the user scenarios",
            "IndoScenarioTextClassification": "Given a user utterance as query, find the user scenarios",
            "VietnameseScenarioTextClassification": "Given a user utterance as query, find the user scenarios",
            "TagalogScenarioTextClassification": "Given a user utterance as query, find the user scenarios",
            "MalayScenarioTextClassification": "Given a user utterance as query, find the user scenarios",
            "KhmerScenarioTextClassification": "Given a user utterance as query, find the user scenarios",
            "TamilScenarioTextClassification": "Given a user utterance as query, find the user scenarios",
            "WongnaiReviewsTextClassification": "Classify the given restaurant review into its appropriate rating category",
            "WisesightSentimentTextClassification": "Classify the sentiment of a given media messages as either positive, negative, or neutral",
            "GeneratedReviewsENTHTextClassification": "Classify the sentiment of a given product reviews as either accepted or rejected",
            "ThaiSentimentTextClassification": "Classify the sentiment of a given text as either positive or negative",
            "IndoSentimentTextClassification": "Classify the sentiment of a given text as either positive or negative",
            "VietnameseSentimentTextClassification": "Classify the sentiment of a given text as either positive or negative",
            "IndoSMSATextClassification": "Classify the sentiment of a given comments and reviews as either positive, negative, or neutral",
            "IndoEMOTTextClassification": "Classify the emotion expressed in the given Twitter message into one of the five emotions: anger, happy, sadness, fear, and love",
            "IndoClickbaitTextClassification": "Classify news headlines into clickbait or non-clickbait",
            "KhmerBookmebusReviewsTextClassification": "Classify the given bookmebus reviews into its appropriate rating category",
            "KhmerNewsTextClassification": "Classify news article on traffic accident into accident or non-accident",
            "TagalogProfanityTextClassification": "Classify text into profanity or non-profanity",
            "TagalogFakenewsTextClassification": "Classify fake news articles into fake news or non-fake news",
            "TagalogShopeeReviewsTextClassification": "Classify the given shopee reviews into its appropriate rating category",
            "HatespeechFilipinoTextClassification": "Classify text into hatespeech or non-hatespeech",
            "VietnameseStudentFeedbackTextClassification": "Classify students’ feedback into positive, negative, or neutral",
            "VLSP2016SentimentTextClassification": "Classify text into positive, negative, or neutral",
            "MalayNewsSentimentTextClassification": "Classify the sentiment of a given news as either positive, negative, or neutral",
            "TamilNewsTextClassification": "Classify news articles into its appropriate topic",
            "TamilmurasuNewsTextClassification": "Classify news articles into its appropriate topic",
            "ThuraMyanmarNewsClassification": "Classify text into its appropriate category",
            "KhineMyanmarNewsClassification": "Classify text into its appropriate category",
            "BurmeseSEATranslationeseResampledClassification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "BurmeseGKLMIPSentimentClassification": "Classify text into its appropriate category",
            "BurmeseSIB200Classification": "Classify text into its appropriate category",
            "MyanmarNewsClassification": "Classify news articles into its appropriate topic",
            "ThaiSIB200Classification": "Classify text into its appropriate topic",
            "ThaiEmojiClassification": "Classify the emotion expressed in the given text into appropriate category",
            "The40ThaiChildrenStoriesClassification": "Classify text into its appropriate category",
            "ThaiTCAS61Classification": "Classify text into positive or negative",
            "ThaiReviewShoppingClassification": "Classify text into positive or negative",
            "ThaiGeneralAmyClassification": "Classify text into positive or negative",
            "ThaiLimeSodaClassification": "Classify text in the healthcare domain into fake news or non-fake news",
            "ThaiKrathu500Classification": "Classify text into positive, negative, or neutral",
            "ThaiCyberbullyingLGBTClassification": "Classify the given cyberbully lgbt into its appropriate category",
            "ThaiDepressionClassification": "Classify text into depression or non depression",
            "ThaiSEATranslationeseResampledClassification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "IndoSIB200Classification": "Classify text into its appropriate topic",
            "IndoGooglePlayReviewClassification": "Classify text into positive, negative, or neutral",
            "IndoHoaxNewsClassification": "Classify text into its appropriate category",
            "IndoHSDNofaauliaClassification": "Classify text into its appropriate category",
            "IndoHateSpeechClassification": "Classify text into its appropriate category",
            "IndoVaccinesTweetsClassification": "Classify text into its appropriate category",
            "IndoEmotionOpinionClassification": "Classify text into its appropriate category",
            "IndoSentEmoMobileAppsClassification": "Classify text into positive, negative, or neutral",
            "IndoLEMSentimentClassification": "Classify text into its appropriate category",
            "IndoMinangClassification": "Classify text into positive or negative",
            "IndoIMDBClassification": "Classify text into its appropriate category",
            "IndoNusaXClassification": "Classify text into positive, negative, or neutral",
            "IndoSentimentAnalysisClassification": "Classify text into its appropriate category",
            "IndoEmotCMTClassification": "Classify text into its appropriate category",
            "IndoJaDiIdeClassification": "Classify text into its appropriate category",
            "IndoNewsDatasetClassification": "Classify text into its appropriate category",
            "IndoABUSIVEClassification": "Classify text into its appropriate category",
            "IndonglishClassification": "Classify text into its appropriate category",
            "IndoSpamidPairClassification": "Classify text into its appropriate category",
            "IndoAbusiveNewsCommentClassification": "Classify text into its appropriate category",
            "IndoSEATranslationeseResampledClassification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "VietnameseSIB200Classification": "Classify text into its appropriate topic",
            "VietnameseSpamReviewsClassification": "Classify text into its appropriate category",
            "VietnameseUITVSMECClassification": "Classify text into its appropriate category",
            "VietnameseViOCDClassification": "Classify text into its appropriate category",
            "VietnameseUITVIONClassification": "Classify text into its appropriate category",
            "VietnamesePhoATISClassification": "Classify text into its appropriate category",
            "VietnameseUITViHSDClassification": "Classify text into its appropriate category",
            "VietnameseUITViCTSDClassification": "Classify text into its appropriate category",
            "VietnameseUITViSFDClassification": "Classify text into its appropriate category",
            "VietnameseUITVSFCClassification": "Classify text into its appropriate category",
            "VietnameseSEATranslationeseResampledClassification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "TagalogSIB200Classification": "Classify text into its appropriate topic",
            "EMoTES3KClassification": "Classify text into its appropriate category",
            "FilipinoTiktokHatespeechClassification": "Classify text into its appropriate category",
            "TyphoonYolandaTweetsClassification": "Classify text into its appropriate category",
            "FilipinoLazadaReviewClassification": "Classify text into its appropriate category",
            "TagalogSEATranslationeseResampledClassification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "MalayTweetsClassification": "Classify text into positive, negative, or neutral",
            "MalaySEATranslationeseResampledClassification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "KhmerSIB200Classification": "Classify text into its appropriate topic",
            "KhmerSEATranslationeseResampledClassification": "Classify text into Human-translated, Machine-translated, or Neutral",

        }
        

        return instruction_dict.get(task_name)