def get_instruction(task_type, task_name):
    if task_type == "STS":
        return "Retrieve semantically similar text."

    if task_type == "BitextMining":
        return "Retrieve parallel sentences."

    if task_type == "PairClassification":
        return "Retrieve semantically similar text."

    if task_type == "InstructionRetrieval":
        return "Given a instruction and a context, retrieve the most relevant context that answer the question.",

    if task_type == "MultiLabelTextClassification":
        instruction_dict = {
            "Prachathai67k_tha_MultiLabelClassification": "Classify the given news articles into its appropriate topics",
            "Prachathai67k_mya_MultiLabelClassification": "Classify the given news articles into its appropriate topics",
            "TrueVoiceIntent_tha_MultiLabelClassification": "Given a call center query, find the corresponding intents",
            "CASA_ind_MultiLabelClassification": "Classify the sentiment expressed in the given car reviews text from the online automobile platform",
            "HoASA_ind_MultiLabelClassification": "Classify the sentiment expressed in the given hotel reviews text from the hotel aggregator platform",
            "VLSP2018SAHotel_vie_MultiLabelClassification": "Classify the sentiment expressed in the given hotel reviews text",
            "VLSP2018SARestaurantMultiLabelTextClassification": "Classify the sentiment expressed in the given restaurant reviews text",
            "VLSP2018SARestaurant_vie_MultiLabelClassification": "Classify the given tweets into its appropriate classes",
            "HateSpeech_ind_MultiLabelClassification": "Classify the given tweets into its appropriate classes",
            "Netifier_ind_MultiLabelClassification": "Classify the given social media text toxicity into its appropriate classes",
            "GKLMIPNews_khm_MultiLabelClassification": "Classify the given news into its appropriate classes",
            "Dengue_fil_MultiLabelClassification": "Classify the given text into its appropriate classes",
        }

        return instruction_dict.get(task_name)

    if task_type == "QARetrieval":
        instruction_dict = {
            "TyDiQA_tha_QARetrieval": "Given a passage that is guaranteed to contain the answer, retrieve relevant passages that answer the query.",
            "TyDiQA_ind_QARetrieval": "Given a passage that is guaranteed to contain the answer, retrieve relevant passages that answer the query.",
            "MIRACL_tha_QARetrieval": "Given a query and a set of documents, retrieve the documents most relevant to answering the query.",
            "MIRACL_ind_QARetrieval": "Given a query and a set of documents, retrieve the documents most relevant to answering the query.",
            "XQuAD_tha_QARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "XQuAD_vie_QARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "ViQuAD2_0_vie_QARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "MLQA_vie_QARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "MLDR_tha_QARetrieval": "Given a query and a long documents, retrieve the documents most relevant to answering the query.",
            "IndicQA_tam_QARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "IAppWiki_tha_QARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "Microbiology1K_mya_QARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "Agricutlure1K_mya_QARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "AskCovidDrBot_mya_QARetrieval": "Given a query and a passage, retrieve the most relevant passage that answer the query.",
            "ACIQuAD_ind_QARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "QASiNa_ind_QARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "IDKMRC_ind_QARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "IndoQA_ind_QARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "WangchanXLegalThaiCCLRAG_tha_QARetrieval": "Given a question and a passage, retrieve the most relevant passage that answer the question.",
            "WangchanXSyntheticInstructThai120k_tha_QARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "ThaiWikiQA_tha_QARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "ChatGPTOpenQA_zsm_QARetrieval": "Given a question and a paragraph, retrieve the most relevant paragraph that answer the question.",
            "IndoNLG_ind_QARetrieval": "Given a question and a context, retrieve the most relevant context that answer the question.",
            "ContextSearch_vie_QARetrieval": "Given a query and a context, retrieve the most relevant context that answer the question.",
        }

        return instruction_dict.get(task_name)


    if task_type == "TextClassification":
        instruction_dict = {
            "MassiveIntent_tha_Classification": "Given a user utterance as query, find the user intents",
            "MassiveIntent_ind_Classification": "Given a user utterance as query, find the user intents",
            "MassiveIntent_vie_Classification": "Given a user utterance as query, find the user intents",
            "MassiveIntent_fil_Classification": "Given a user utterance as query, find the user intents",
            "MassiveIntent_zsm_Classification": "Given a user utterance as query, find the user intents",
            "MassiveIntent_khm_Classification": "Given a user utterance as query, find the user intents",
            "MassiveIntent_tam_lassification": "Given a user utterance as query, find the user intents",
            "MassiveScenario_tha_Classification": "Given a user utterance as query, find the user scenarios",
            "MassiveScenario_ind_Classification": "Given a user utterance as query, find the user scenarios",
            "MassiveScenario_vie_TextClassification": "Given a user utterance as query, find the user scenarios",
            "MassiveScenario_fil_Classification": "Given a user utterance as query, find the user scenarios",
            "MassiveScenario_zsm_Classification": "Given a user utterance as query, find the user scenarios",
            "MassiveScenario_khm_Classification": "Given a user utterance as query, find the user scenarios",
            "MassiveScenario_tam_Classification": "Given a user utterance as query, find the user scenarios",
            "WongnaiReviews_tha_Classification": "Classify the given restaurant review into its appropriate rating category",
            "WisesightSentiment_tha_Classification": "Classify the sentiment of a given media messages as either positive, negative, or neutral",
            "GeneratedReviewsENTH_tha_Classification": "Classify the sentiment of a given product reviews as either accepted or rejected",
            "MassiveSentiment_tha_Classification": "Classify the sentiment of a given text as either positive or negative",
            "Sentiment_ind_Classification": "Classify the sentiment of a given text as either positive or negative",
            "Sentiment_vie_Classification": "Classify the sentiment of a given text as either positive or negative",
            "SMSA_ind_Classification": "Classify the sentiment of a given comments and reviews as either positive, negative, or neutral",
            "EMOT_ind_Classification": "Classify the emotion expressed in the given Twitter message into one of the five emotions: anger, happy, sadness, fear, and love",
            "Clickbait_ind_Classification": "Classify news headlines into clickbait or non-clickbait",
            "BookmebusReviews_khm_Classification": "Classify the given bookmebus reviews into its appropriate rating category",
            "News_khm_Classification": "Classify news article on traffic accident into accident or non-accident",
            "Profanity_fil_Classification": "Classify text into profanity or non-profanity",
            "Fakenews_fil_Classification": "Classify fake news articles into fake news or non-fake news",
            "ShopeeReviews_fil_Classification": "Classify the given shopee reviews into its appropriate rating category",
            "Hatespeech_fil_TextClassification": "Classify text into hatespeech or non-hatespeech",
            "StudentFeedback_vie_Classification": "Classify students’ feedback into positive, negative, or neutral",
            "VLSP2016Sentiment_vie_Classification": "Classify text into positive, negative, or neutral",
            "News_zsm_Classification": "Classify the sentiment of a given news as either positive, negative, or neutral",
            "News_tam_Classification": "Classify news articles into its appropriate topic",
            "MurasuNews_tam_Classification": "Classify news articles into its appropriate topic",
            "ThuraMyanmarNews_mya_Classification": "Classify text into its appropriate category",
            "KhineMyanmarNews_may_Classification": "Classify text into its appropriate category",
            "SEATranslationeseResampled_mya_Classification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "GKLMIPSentiment_mya_Classification": "Classify text into its appropriate category",
            "SIB200_may_Classification": "Classify text into its appropriate category",
            "News_mya_Classification": "Classify news articles into its appropriate topic",
            "SIB200_tha_Classification": "Classify text into its appropriate topic",
            "Emoji_tha_Classification": "Classify the emotion expressed in the given text into appropriate category",
            "The40ThaiChildrenStories_tha_Classification": "Classify text into its appropriate category",
            "TCAS61_tha_Classification": "Classify text into positive or negative",
            "ReviewShopping_tha_Classification": "Classify text into positive or negative",
            "GeneralAmy_tha_Classification": "Classify text into positive or negative",
            "LimeSoda_tha_Classification": "Classify text in the healthcare domain into fake news or non-fake news",
            "Krathu500_tha_Classification": "Classify text into positive, negative, or neutral",
            "CyberbullyingLGBT_tha_Classification": "Classify the given cyberbully lgbt into its appropriate category",
            "Depression_tha_Classification": "Classify text into depression or non depression",
            "SEATranslationeseResampled_tha_Classification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "SIB200_ind_Classification": "Classify text into its appropriate topic",
            "GooglePlayReview_ind_Classification": "Classify text into positive, negative, or neutral",
            "HoaxNews_ind_Classification": "Classify text into its appropriate category",
            "HSDNofaaulia_ind_Classification": "Classify text into its appropriate category",
            "HateSpeech_ind_Classification": "Classify text into its appropriate category",
            "VaccinesTweets_ind_Classification": "Classify text into its appropriate category",
            "EmotionOpinion_ind_Classification": "Classify text into its appropriate category",
            "SentEmoMobileApps_ind_Classification": "Classify text into positive, negative, or neutral",
            "LEMSentiment_ind_Classification": "Classify text into its appropriate category",
            "Minang_ind_Classification": "Classify text into positive or negative",
            "IMDB_ind_Classification": "Classify text into its appropriate category",
            "NusaX_ind_Classification": "Classify text into positive, negative, or neutral",
            "SentimentAnalysis_ind_Classification": "Classify text into its appropriate category",
            "EmotCMT_ind_Classification": "Classify text into its appropriate category",
            "JaDiIde_ind_Classification": "Classify text into its appropriate category",
            "NewsDataset_ind_Classification": "Classify text into its appropriate category",
            "ABUSIVE_ind_Classification": "Classify text into its appropriate category",
            "Indonglish_ind_Classification": "Classify text into its appropriate category",
            "SpamidPair_ind_Classification": "Classify text into its appropriate category",
            "AbusiveNewsComment_ind_Classification": "Classify text into its appropriate category",
            "SEATranslationeseResampled_ind_Classification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "SIB200_vie_Classification": "Classify text into its appropriate topic",
            "SpamReviews_vie_Classification": "Classify text into its appropriate category",
            "UITVSMEC_vie_Classification": "Classify text into its appropriate category",
            "ViOCD_vie_Classification": "Classify text into its appropriate category",
            "UITVION_vie_Classification": "Classify text into its appropriate category",
            "PhoATIS_vie_Classification": "Classify text into its appropriate category",
            "UITViHSD_vie_Classification": "Classify text into its appropriate category",
            "UITViCTSD_vie_Classification": "Classify text into its appropriate category",
            "UITViSFD_vie_Classification": "Classify text into its appropriate category",
            "UITVSFC_vie_Classification": "Classify text into its appropriate category",
            "SEATranslationeseResampled_vie_Classification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "SIB200_fil_Classification": "Classify text into its appropriate topic",
            "EMoTES3K_fil_Classification": "Classify text into its appropriate category",
            "TiktokHatespeech_fil_Classification": "Classify text into its appropriate category",
            "TyphoonYolandaTweets_fil_Classification": "Classify text into its appropriate category",
            "LazadaReview_fil_Classification": "Classify text into its appropriate category",
            "SEATranslationeseResampled_fil_Classification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "Tweets_zsm_Classification": "Classify text into positive, negative, or neutral",
            "SEATranslationeseResampled_zsm_Classification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "SIB200_khm_Classification": "Classify text into its appropriate topic",
            "SEATranslationeseResampled_khm_Classification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "PHElectionsTD_fil_Classification": "Classify text into its appropriate topic",
            "PHElectionsSA_fil_Classification": "Classify text into positive, negative, or neutral",
            "News_lao_Classification": "Classify text into its appropriate category",
            "SIB200_lao_Classification": "Classify text into its appropriate topic",
            "SEATranslationeseResampled_lao_Classification": "Classify text into Human-translated, Machine-translated, or Neutral",
            "MADLAD400_tet_Classification": "Classify text into Tetum or English language",
        }
        

        return instruction_dict.get(task_name)