from .ThaiXNLI import *
from .IndoNLI import *
from .MalayXNLI import *
from .KhmerXNLI import *
from .VietnameseXNLI import *
from .NewsPHNLI import *
from .TamilXNLI import *
from .IndoWReTE import *
from .BurmeseXNLI import *
from .IndoSQuADNLIPairClassification import *
from .IndoTyDIQANLIPairClassification import *
from .IndoIDKMRCNLIPairClassification import *
from .IndoMultilingualNLI26lang2mil7PairClassification import *
from .VietnameseMultilingualNLI26lang2mil7PairClassification import *