from .IDKMRCNLI_ind_PairClassification import *
from .IndoNLI_ind_PairClassification import *
from .MultilingualNLI26lang2mil7_ind_PairClassification import *
from .SQuADNLI_ind_PairClassification import *
from .TyDIQANLI_ind_PairClassification import *
from .WReTE_ind_PairClassification import *
from .XNLI_tha_PairClassification import *
from .MultilingualNLI26lang2mil7_vie_PairClassification import *
from .XNLI_vie_PairClassification import *
from .NewsPHNLI_fil_PairClassification import *
from .PAWS_fil_PairClassification import *
from .XNLI_mya_PairClassification import *
from .XNLI_tam_PairClassification import *
from .XNLI_khm_PairClassification import *
from .XNLI_zsm_PairClassification import *
from .XNLI_lao_PairClassification import *