from .ThaiTED2020 import *
from .IndoTED2020 import *
from .MalayTED2020 import *
from .KhmerTED2020 import *
from .VietnameseTED2020 import *
from .TagalogTED2020 import *
from .TamilTED2020 import *
from .ThaiQED import *
from .IndoQED import *
from .MalayQED import *
from .KhmerQED import *
from .VietnameseQED import *
from .TagalogQED import *
from .TamilQED import *
from .ThaiTatoeba import *
from .IndoTatoeba import *
from .KhmerTatoeba import *
from .VietnameseTatoeba import *
from .TagalogTatoeba import *
from .TamilTatoeba import *
from .IndoBiblenlp import *
from .VietnameseBiblenlp import *
from .TagalogBiblenlp import *
from .ThaiBiblenlp import *
from .TamilBiblenlp import *
from .TamilIN22Conv import *
from .TamilIN22Gen import *
from .IndoNusaxMiners import *
from .ThaiFlores import *
from .IndoFlores import *
from .VietnameseFlores import *
from .TagalogFlores import *
from .KhmerFlores import *
from .TamilFlores import *
from .ThaiNTREX import *
from .IndoNTREX import *
from .VietnameseNTREX import *
from .TagalogNTREX import *
from .KhmerNTREX import *
from .TamilNTREX import *
from .BurmeseTED2020 import *
from .BurmeseQED import *
from .BurmeseTatoeba import *
from .BurmeseBiblenlp import *
from .BurmeseFlores import *
from .BurmeseNTREX import *