from .ThaiTED2020 import *
from .IndoTED2020 import *
from .MalayTED2020 import *
from .KhmerTED2020 import *
from .VietnameseTED2020 import *
from .TagalogTED2020 import *
from .TamilTED2020 import *
from .ThaiQED import *
from .IndoQED import *
from .MalayQED import *
from .KhmerQED import *
from .VietnameseQED import *
from .TagalogQED import *
from .TamilQED import *
from .ThaiTatoeba import *
from .IndoTatoeba import *
from .KhmerTatoeba import *
from .VietnameseTatoeba import *
from .TagalogTatoeba import *
from .TamilTatoeba import *