from .ThaiTED2020 import *
from .IndoTED2020 import *
from .MalayTED2020 import *
from .KhmerTED2020 import *
from .VietnameseTED2020 import *
from .TagalogTED2020 import *
from .TamilTED2020 import *
from .ThaiQED import *
from .IndoQED import *
from .MalayQED import *
from .KhmerQED import *
from .VietnameseQED import *
from .TagalogQED import *
from .TamilQED import *
from .ThaiTatoeba import *
from .IndoTatoeba import *
from .KhmerTatoeba import *
from .VietnameseTatoeba import *
from .TagalogTatoeba import *
from .TamilTatoeba import *
from .IndoBiblenlp import *
from .VietnameseBiblenlp import *
from .TagalogBiblenlp import *
from .ThaiBiblenlp import *
from .TamilBiblenlp import *
from .TamilIN22Conv import *
from .TamilIN22Gen import *
from .IndoNusaxMiners import *
from .ThaiFlores import *
from .IndoFlores import *
from .VietnameseFlores import *
from .TagalogFlores import *
from .KhmerFlores import *
from .TamilFlores import *
from .ThaiNTREX import *
from .IndoNTREX import *
from .VietnameseNTREX import *
from .TagalogNTREX import *
from .KhmerNTREX import *
from .TamilNTREX import *
from .BurmeseTED2020 import *
from .BurmeseQED import *
from .BurmeseTatoeba import *
from .BurmeseBiblenlp import *
from .BurmeseFlores import *
from .BurmeseNTREX import *
from .ThaiTALPCoBitextMining import *
from .IndoTALPCoBitextMining import *
from .VietnameseTALPCoBitextMining import *
from .MalayTALPCoBitextMining import *
from .BurmeseTALPCoBitextMining import *
from .ThaiSoftwareDocumentationBitextMining import *
from .IndoSoftwareDocumentationBitextMining import *
from .VietnameseSoftwareDocumentationBitextMining import *
from .MalaySoftwareDocumentationBitextMining import *
from .ThaiALTBitextMining import *
from .IndoALTBitextMining import *
from .VietnameseALTBitextMining import *
from .FilipinoALTBitextMining import *
from .KhmerALTBitextMining import *
from .MalayALTBitextMining import *
from .BurmeseALTBitextMining import *
from .LaoALTBitextMining import *
from .LaoTED2020BitextMining import *
from .LaoQEDBitextMining import *
from .LaoTatoebaBitextMining import *
from .LaoNTREXBitextMining import *
from .LaoFloresBitextMining import *
from .SCBMTEnTh2020BitextMining import *
from .ThaiUSEmbassyBitextMining import *
from .IndoIdenticBitextMining import *
from .IndoNLGBitextMining import *
from .IndoReligiousBitextMining import *
from .IndoGeneralBitextMining import *
from .IndoNewsBitextMining import *