from .ACIQuAD_ind_QARetrieval import *
from .IDKMRC_ind_QARetrieval import *
from .IndoNLG_ind_QARetrieval import *
from .IndoQA_ind_QARetrieval import *
from .MIRACL_ind_QARetrieval import *
from .QASiNa_ind_QARetrieval import *
from .TyDiQA_ind_QARetrieval import *
from .IAppWiki_tha_QARetrieval import *
from .MIRACL_tha_QARetrieval import *
from .MLDR_tha_QARetrieval import *
from .ThaiWikiQA_tha_QARetrieval import *
from .TyDiQA_tha_QARetrieval import *
from .WangchanXLegalThaiCCLRAG_tha_QARetrieval import *
from .WangchanXSyntheticInstructThai120k_tha_QARetrieval import *
from .XQuAD_tha_QARetrieval import *
from .MLQA_vie_QARetrieval import *
from .ViQuAD2_0_vie_QARetrieval import *
from .XQuAD_vie_QARetrieval import *
from .Microbiology1K_mya_QARetrieval import *
from .Agricutlure1K_mya_QARetrieval import *
from .AskCovidDrBot_mya_QARetrieval import *
from .IndicQA_tam_QARetrieval import *
from .ChatGPTOpenQA_zsm_QARetrieval import *
