from .ThaiXQuAD import *
from .VietnameseXQuAD import *
from .ThaiMIRACL import *
from .IndoMIRACL import *
from .ThaiTyDiQA import *
from .IndoTyDiQA import *
from .VietnameseMLQA import *
from .ViQuAD2_0 import *
from .TamilIndicQA import *
from .ThaiMLDR import *