from .CASA_ind_MultiLabelClassification import *
from .HateSpeech_ind_MultiLabelClassification import *
from .HoASA_ind_MultiLabelClassification import *
from .Netifier_ind_MultiLabelClassification import *
from .Prachathai67k_tha_MultiLabelClassification import *
from .TrueVoiceIntent_tha_MultiLabelClassification import *
from .VLSP2018SAHotel_vie_MultiLabelClassification import *
from .VLSP2018SARestaurant_vie_MultiLabelClassification import *
from .Dengue_fil_MultiLabelClassification import *
from .GKLMIPNews_khm_MultiLabelClassification import *