from .STSBenchmark_ind_STS import *
from .SemRel2024_ind_STS import *
from .STSBenchmark_tha_STS import *
from .STS17_tha_STS import *
from .STS22_tha_STS import *
from .Biosses_tha_STS import *
from .STS24_tha_STS import *
from .BiossesCrosslingual_tha_STS import *
from .STS17Crosslingual_tha_STS import *
from .STS22Crosslingual_tha_STS import *
from .STS24Crosslingual_tha_STS import *
from .STSBenchmark_vie_STS import *
from .STSBenchmark_fil_STS import *
from .STSBenchmark_mya_STS import *
from .Biosses_mya_STS import *
from .STS17_mya_STS import *
from .STS22_mya_STS import *
from .STS24_mya_STS import *
from .BiossesCrosslingual_mya_STS import *
from .STS17Crosslingual_mya_STS import *
from .STS22Crosslingual_mya_STS import *
from .STS24Crosslingual_mya_STS import *
from .STSBenchmark_tam_STS import *
from .IndicCrosslingual_tam_STS import *
from .STSBenchmark_khm_STS import *
from .STSBenchmark_zsm_STS import *
from .STSBenchmark_lao_STS  import *
