from .WisesightSentiment import *
from .WongnaiReviews import *
from .GeneratedReviewsENTH import *
from .IndoIntentClassification import *
from .IndoScenarioClassification import *
from .IndoEMOT import *
from .IndoSMSA import *
from .VietnameseIntentClassification import *
from .VietnameseScenarioClassification import *
from .VLSP2016Sentiment import *
from .TagalogIntentClassification import *
from .TagalogScenarioClassification import *
from .HatespeechFilipinoClassification import *
from .MalayIntentClassification import *
from .MalayScenarioClassification import *
from .MalayNewsSentiment import *
from .KhmerIntentClassification import *
from .KhmerScenarioClassification import *
from .KhmerBookmebusReviews import *
from .KhmerNewsClassification import *
from .TamilIntentClassification import *
from .TamilScenarioClassification import *
from .TamilNewsClassification import *
from .TamilmurasuNewsClassification import *
from .ThaiIntentClassification import *
from .ThaiScenarioClassification import *
from .ThaiSentimentClassification import *
from .IndoSentimentClassification import *
from .VietnameseSentimentClassification import *
from .IndoClickbaitClassification import *
from .TagalogShopeeReviewsClassification import *
from .VietnameseStudentFeedbackClassification import *
from .TagalogProfanityClassification import *
from .TagalogFakenewsClassification import *
from .MyanmarNewsClassification import *
from .ThuraMyanmarNewsClassification import *
from .KhineMyanmarNewsClassification import *
from .BurmeseGKLMIPSentimentClassification import *
from .BurmeseSEATranslationeseResampledClassification import *
from .ThaiSEATranslationeseResampledClassification import *
from .IndoSEATranslationeseResampledClassification import *
from .VietnameseSEATranslationeseResampledClassification import *
from .TagalogSEATranslationeseResampledClassification import *
from .MalaySEATranslationeseResampledClassification import *
from .KhmerSEATranslationeseResampledClassification import *
from .BurmeseSIB200Classification import *
from .ThaiSIB200Classification import *
from .IndoSIB200Classification import *
from .VietnameseSIB200Classification import *
from .TagalogSIB200Classification import *
from .KhmerSIB200Classification import *
from .ThaiEmojiClassification import *
from .The40ThaiChildrenStoriesClassification import *
from .ThaiTCAS61Classification import *
from .ThaiReviewShoppingClassification import *
from .ThaiGeneralAmyClassification import *
from .ThaiLimeSodaClassification import *
from .ThaiKrathu500Classification import *
from .ThaiCyberbullyingLGBTClassification import *
from .ThaiDepressionClassification import *
from .EMoTES3KClassification import *
from .IndoGooglePlayReviewClassification import *
from .FilipinoTiktokHatespeechClassification import *
from .IndoHoaxNewsClassification import *
from .IndoHSDNofaauliaClassification import *
from .IndoHateSpeechClassification import *
from .IndoVaccinesTweetsClassification import *
from .TyphoonYolandaTweetsClassification import *
from .IndoEmotionOpinionClassification import *
from .IndoSentEmoMobileAppsClassification import *
from .MalayTweetsClassification import *
from .IndoLEMSentimentClassification import *
from .VietnameseSpamReviewsClassification import *
from .IndoMinangClassification import *
from .IndoIMDBClassification import *
from .IndoNusaXClassification import *
from .VietnameseUITVSMECClassification import *
from .VietnameseViOCDClassification import *
from .IndoSentimentAnalysisClassification import *
from .VietnameseUITVIONClassification import *
from .IndoEmotCMTClassification import *
from .IndoJaDiIdeClassification import *
from .VietnamesePhoATISClassification import *
from .IndoNewsDatasetClassification import *
from .VietnameseUITViHSDClassification import *
from .IndoABUSIVEClassification import *
from .VietnameseUITViCTSDClassification import *
from .FilipinoLazadaReviewClassification import *
from .IndonglishClassification import *
from .IndoSpamidPairClassification import *
from .VietnameseUITViSFDClassification import *
from .VietnameseUITVSFCClassification import *
from .IndoAbusiveNewsCommentClassification import *