from .WisesightSentiment import *
from .WongnaiReviews import *
from .GeneratedReviewsENTH import *
from .IndoIntentClassification import *
from .IndoScenarioClassification import *
from .IndoEMOT import *
from .IndoSMSA import *
from .VietnameseIntentClassification import *
from .VietnameseScenarioClassification import *
from .VLSP2016Sentiment import *
from .TagalogIntentClassification import *
from .TagalogScenarioClassification import *
from .HatespeechFilipinoClassification import *
from .MalayIntentClassification import *
from .MalayScenarioClassification import *
from .MalayNewsClassification import *
from .KhmerIntentClassification import *
from .KhmerScenarioClassification import *
from .KhmerBookmebusReviews import *
from .KhmerNewsClassification import *
from .TamilIntentClassification import *
from .TamilScenarioClassification import *
from .TamilNewsClassification import *
from .TamilmurasuNewsClassification import *
