from .WisesightSentiment import *
from .WongnaiReviews import *
from .GeneratedReviewsENTH import *
from .IndoIntentClassification import *
from .IndoScenarioClassification import *
from .IndoEMOT import *
from .IndoSMSA import *
from .VietnameseIntentClassification import *
from .VietnameseScenarioClassification import *
from .VLSP2016Sentiment import *
from .TagalogIntentClassification import *
from .TagalogScenarioClassification import *
from .HatespeechFilipinoClassification import *
from .MalayIntentClassification import *
from .MalayScenarioClassification import *
from .MalayNewsSentiment import *
from .KhmerIntentClassification import *
from .KhmerScenarioClassification import *
from .KhmerBookmebusReviews import *
from .KhmerNewsClassification import *
from .TamilIntentClassification import *
from .TamilScenarioClassification import *
from .TamilNewsClassification import *
from .TamilmurasuNewsClassification import *
from .ThaiIntentClassification import *
from .ThaiScenarioClassification import *
from .ThaiSentimentClassification import *
from .IndoSentimentClassification import *
from .VietnameseSentimentClassification import *
from .IndoClickbaitClassification import *
from .TagalogShopeeReviewsClassification import *
from .VietnameseStudentFeedbackClassification import *
from .TagalogProfanityClassification import *
from .TagalogFakenewsClassification import *

