from .WisesightSentiment_tha_Classification import *
from .WongnaiReviews_tha_Classification import *
from .GeneratedReviewsENTH_tha_Classification import *
from .MassiveIntent_ind_Classification import *
from .MassiveScenario_ind_Classification import *
from .EMOT_ind_Classification import *
from .SMSA_ind_Classification import *
from .MassiveIntent_vie_Classification import *
from .MassiveScenario_vie_Classification import *
from .VLSP2016Sentiment_vie_Classification import *
from .MassiveIntent_fil_Classification import *
from .MassiveScenario_fil_Classification import *
from .Hatespeech_fil_Classification import *
from .MassiveIntent_zsm_Classification import *
from .MassiveScenario_zsm_Classification import *
from .NewsSentiment_zsm_Classification import *
from .MassiveIntent_khm_Classification import *
from .MassiveScenario_khm_Classification import *
from .BookmebusReviews_khm_Classification import *
from .News_khm_Classification import *
from .MassiveIntent_tam_Classification import *
from .MassiveScenario_tam_Classification import *
from .News_tam_Classification import *
from .MurasuNews_tam_Classification import *
from .MassiveIntent_tha_Classification import *
from .MassiveScenario_tha_Classification import *
from .MassiveSentiment_tha_Classification import *
from .MassiveSentiment_ind_Classification import *
from .MassiveSentiment_vie_Classification import *
from .Clickbait_ind_Classification import *
from .ShopeeReviews_fil_Classification import *
from .StudentFeedback_vie_Classification import *
from .Profanity_fil_Classification import *
from .Fakenews_fil_Classification import *
from .News_mya_Classification import *
from .ThuraMyanmarNews_mya_Classification import *
from .KhineMyanmarNews_mya_Classification import *
from .GKLMIPSentiment_mya_Classification import *
from .SEATranslationeseResampled_mya_Classification import *
from .SEATranslationeseResampled_tha_Classification import *
from .SEATranslationeseResampled_ind_Classification import *
from .SEATranslationeseResampled_vie_Classification import *
from .SEATranslationeseResampled_fil_Classification import *
from .SEATranslationeseResampled_zsm_Classification import *
from .SEATranslationeseResampled_khm_Classification import *
from .SEATranslationeseResampled_lao_Classification import *
from .SIB200_mya_Classification import *
from .SIB200_tha_Classification import *
from .SIB200_ind_Classification import *
from .SIB200_vie_Classification import *
from .SIB200_fil_Classification import *
from .SIB200_khm_Classification import *
from .SIB200_lao_Classification import *
from .Emoji_tha_Classification import *
from .The40ThaiChildrenStories_tha_Classification import *
from .TCAS61_tha_Classification import *
from .ReviewShopping_tha_Classification import *
from .GeneralAmy_tha_Classification import *
from .LimeSoda_tha_Classification import *
from .Krathu500_tha_Classification import *
from .CyberbullyingLGBT_tha_Classification import *
from .Depression_tha_Classification import *
from .EMoTES3K_fil_Classification import *
from .GooglePlayReview_ind_Classification import *
from .TiktokHatespeech_fil_Classification import *
from .HoaxNews_ind_Classification import *
from .HSDNofaaulia_ind_Classification import *
from .HateSpeech_ind_Classification import *
from .VaccinesTweets_ind_Classification import *
from .TyphoonYolandaTweets_fil_Classification import *
from .EmotionOpinion_ind_Classification import *
from .SentEmoMobileApps_ind_Classification import *
from .Tweets_zsm_Classification import *
from .LEMSentiment_ind_Classification import *
from .SpamReviews_vie_Classification import *
from .Minang_ind_Classification import *
from .IMDB_ind_Classification import *
from .NusaX_ind_Classification import *
from .UITVSMEC_vie_Classification import *
from .ViOCD_vie_Classification import *
from .SentimentAnalysis_ind_Classification import *
from .UITVION_vie_Classification import *
from .EmotCMT_ind_Classification import *
from .JaDiIde_ind_Classification import *
from .PhoATIS_vie_Classification import *
from .NewsDataset_ind_Classification import *
from .UITViHSD_vie_Classification import *
from .ABUSIVE_ind_Classification import *
from .UITViCTSD_vie_Classification import *
from .LazadaReview_fil_Classification import *
from .Indonglish_ind_Classification import *
from .SpamidPair_ind_Classification import *
from .UITViSFD_vie_Classification import *
from .AbusiveNewsComment_ind_Classification import *
from .CodeMixed_ind_Classification import *
from .Karonese_ind_Classification import *
from .News_lao_Classification import *
from .MADLAD400_tet_Classification import *
from .PHElectionsSA_fil_Classification import *
from .PHElectionsTD_fil_Classification import *