from .Prachathai67k import *
from .TrueVoiceIntent import *
from .Dengue import *
from .IndoCASA import *
from .IndoHoASA import *
from .VLSP2018SARestaurant import *
from .VLSP2018SAHotel import *
from. IndoHateSpeechMultiLabelClassification import *
from .IndoNetifierMultiLabelClassification import *
from .GKLMIPNewsMultiLabelClassification import *