from .ThaiSTSBenchmarkSTS import *
from .IndoSTSBenchmarkSTS import *
from .MalaySTSBenchmarkSTS import *
from .KhmerSTSBenchmarkSTS import *
from .VietnameseSTSBenchmarkSTS import *
from .TagalogSTSBenchmarkSTS import *
from .TamilSTSBenchmarkSTS import *
from .IndoSemRel2024STS import *
from .ThaiSTS24STS import *
from .ThaiSTS22STS import *
from .ThaiSTS17STS import *
from .ThaiBiossesSTS import *
from .BurmeseSTS24STS import *
from .BurmeseSTS22STS import *
from .BurmeseSTS17STS import *
from .BurmeseBiossesSTS import *
from .ThaiSTS24CrosslingualSTS import *
from .ThaiSTS22CrosslingualSTS import *
from .ThaiSTS17CrosslingualSTS import *
from .ThaiBiossesCrosslingualSTS import *
from .BurmeseSTS24CrosslingualSTS import *
from .BurmeseSTS22CrosslingualSTS import *
from .BurmeseSTS17CrosslingualSTS import *
from .BurmeseBiossesCrosslingualSTS import *
from .TamilIndicCrosslingualSTS import *