from .TED2020_tha_BitextMining import *
from .TED2020_ind_BitextMining import *
from .TED2020_zsm_BitextMining import *
from .TED2020_khm_BitextMining import *
from .TED2020_vie_BitextMining import *
from .TED2020_fil_BitextMining import *
from .TED2020_tam_BitextMining import *
from .QED_tha_BitextMining import *
from .QED_ind_BitextMining import *
from .QED_zsm_BitextMining import *
from .QED_khm_BitextMining import *
from .QED_vie_BitextMining import *
from .QED_fil_BitextMining import *
from .QED_tam_BitextMining import *
from .Tatoeba_tha_BitextMining import *
from .Tatoeba_ind_BitextMining import *
from .Tatoeba_khm_BitextMining import *
from .Tatoeba_vie_BitextMining import *
from .Tatoeba_fil_BitextMining import *
from .Tatoeba_tam_BitextMining import *
from .Biblenlp_ind_BitextMining import *
from .Biblenlp_vie_BitextMining import *
from .Biblenlp_fil_BitextMining import *
from .Biblenlp_tha_BitextMining import *
from .Biblenlp_tam_BitextMining import *
from .IN22Conv_tam_BitextMining import *
from .IN22Gen_tam_BitextMining import *
from .NusaxMiners_ind_BitextMining import *
from .Flores_tha_BitextMining import *
from .Flores_ind_BitextMining import *
from .Flores_vie_BitextMining import *
from .Flores_fil_BitextMining import *
from .Flores_khm_BitextMining import *
from .Flores_tam_BitextMining import *
from .NTREX_tha_BitextMining import *
from .NTREX_ind_BitextMining import *
from .NTREX_vie_BitextMining import *
from .NTREX_fil_BitextMining import *
from .NTREX_khm_BitextMining import *
from .NTREX_tam_BitextMining import *
from .TED2020_mya_BitextMining import *
from .QED_mya_BitextMining import *
from .Tatoeba_mya_BitextMining import *
from .Biblenlp_mya_BitextMining import *
from .Flores_mya_BitextMining import *
from .NTREX_mya_BitextMining import *
from .TALPCo_tha_BitextMining import *
from .TALPCo_ind_BitextMining import *
from .TALPCo_vie_BitextMining import *
from .TALPCo_zsm_BitextMining import *
from .TALPCo_mya_BitextMining import *
from .SoftwareDocumentation_tha_BitextMining import *
from .SoftwareDocumentation_ind_BitextMining import *
from .SoftwareDocumentation_vie_BitextMining import *
from .SoftwareDocumentation_zsm_BitextMining import *
from .ALT_tha_BitextMining import *
from .ALT_ind_BitextMining import *
from .ALT_vie_BitextMining import *
from .ALT_fil_BitextMining import *
from .ALT_khm_BitextMining import *
from .ALT_zsm_BitextMining import *
from .ALT_mya_BitextMining import *
from .ALT_lao_BitextMining import *
from .TED2020_lao_BitextMining import *
from .QED_lao_BitextMining import *
from .Tatoeba_lao_BitextMining import *
from .NTREX_lao_BitextMining import *
from .Flores_lao_BitextMining import *
from .SCBMTEnTh2020_tha_BitextMining import *
from .USEmbassy_tha_BitextMining import *
from .IndoIdentic_ind_BitextMining import *
from .IndoNLG_ind_BitextMining import *
from .IndoReligious_ind_BitextMining import *
from .IndoGeneral_ind_BitextMining import *
from .IndoNews_ind_BitextMining import *
from .QED_tet_BitextMining import *
from .Tatoeba_tet_BitextMining import *
from .MADLAD400_tet_BitextMining import *
from .Embassy_tha_lao_BitextMining import *
from .XLSum_ind_BitextMining import *
from .XLSum_tha_BitextMining import *
from .XLSum_vie_BitextMining import *
from .XLSum_mya_BitextMining import *
from .Liputan6_ind_BitextMining import *
from .ThaiGov_tha_BitextMining import *
from .VSoLSCSum_vie_BitextMining import *
from .ThaiSum_tha_BitextMining import *
from .ALTDialect_ind_tha_BitextMining import *
from .ALTDialect_ind_vie_BitextMining import *
from .ALTDialect_ind_mya_BitextMining import *
from .ALTDialect_ind_fil_BitextMining import *
from .ALTDialect_ind_khm_BitextMining import *
from .ALTDialect_ind_zsm_BitextMining import *
from .ALTDialect_ind_lao_BitextMining import *
from .ALTDialect_tha_vie_BitextMining import *
from .ALTDialect_tha_mya_BitextMining import *
from .ALTDialect_tha_fil_BitextMining import *
from .ALTDialect_tha_khm_BitextMining import *
from .ALTDialect_tha_zsm_BitextMining import *
from .ALTDialect_tha_lao_BitextMining import *
from .ALTDialect_vie_mya_BitextMining import *
from .ALTDialect_vie_fil_BitextMining import *
from .ALTDialect_vie_khm_BitextMining import *
from .ALTDialect_vie_zsm_BitextMining import *
from .ALTDialect_vie_lao_BitextMining import *
from .ALTDialect_mya_fil_BitextMining import *
from .ALTDialect_mya_khm_BitextMining import *
from .ALTDialect_mya_zsm_BitextMining import *
from .ALTDialect_mya_lao_BitextMining import *
from .ALTDialect_fil_khm_BitextMining import *
from .ALTDialect_fil_zsm_BitextMining import *
from .ALTDialect_fil_lao_BitextMining import *
from .ALTDialect_khm_zsm_BitextMining import *
from .ALTDialect_khm_lao_BitextMining import *
from .ALTDialect_zsm_lao_BitextMining import *