from .WangchanThaiInstruct_tha_InstructionRetrieval import *
from .WangchanXSyntheticInstructThai120k_tha_InstructionRetrieval import *
from .AlpacaInstruct_ind_InstructionRetrieval import *
from .Vietnamese52KAlpaca_vie_InstructionRetrieval import *